### PR TITLE
Fixing global compilation command

### PR DESCRIPTION
**Pull request by Kcchouette**

### CODE REVIEW

**Comment by rmanfredi** [comment]
Why do you need to use gmake instead of make?  Which system is that?

**Comment by Kcchouette** [comment]
It seems coming from this line: https://github.com/gtk-gnutella/gtk-gnutella/blob/e720ec628da23cab86bfd3c6f18fc6998435e931/build.sh#L196

I've just done: `./build.sh`
And at this end of this command, I've seen: `Run "gmake install" to install gtk-gnutella`.

Maybe this PR is useless ^^

**Comment by rmanfredi** [comment]
As it was documented above, build.sh already outputs the proper MAKE program name. I'm going to change the README phrasing to reflect that.

**Comment by rmanfredi** [comment]
No need to merge back. closing PR.

**Pull request closed without merging**
